# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PipingServerCheck < Formula
  desc "Check CLI for Piping Server"
  homepage "https://github.com/nwtgck/piping-server-check"
  version "0.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/piping-server-check/releases/download/v0.9.0/piping-server-check-0.9.0-darwin-amd64.tar.gz"
      sha256 "cf582c739e45764c1e6dd9925e639cd13e0c381d1788bb7953cbd572ff2a80fa"

      def install
        bin.install "piping-server-check"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/piping-server-check/releases/download/v0.9.0/piping-server-check-0.9.0-linux-arm64.tar.gz"
      sha256 "c71f65ec37a87b820968b9e7642554353693a8d1df15dfcd60781222b17111c4"

      def install
        bin.install "piping-server-check"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nwtgck/piping-server-check/releases/download/v0.9.0/piping-server-check-0.9.0-linux-armv6.tar.gz"
      sha256 "ea1d3c2abb6151f2bbaf67ec15fcd8d58f6b6ab620efec11cf4963c02ca7e532"

      def install
        bin.install "piping-server-check"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/piping-server-check/releases/download/v0.9.0/piping-server-check-0.9.0-linux-amd64.tar.gz"
      sha256 "a0ba48034cea3607d2cf6372811f56defed6a5dc18b50dd247dadeee1d6e0bc2"

      def install
        bin.install "piping-server-check"
      end
    end
  end
end
